# Generated by Django 5.2.17 on 2026-09-21 10:33

import django.db.models.deletion
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.JSONField(blank=True, default=list, help_text='List of {"key": "...", "label": "...", "content": "..."} objects.', validators=[pages.models.validate_sections])),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.pagecontent')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='pages.pagesections')),
            ],
            options={
                'verbose_name': 'page sections',
                'verbose_name_plural': 'page sections',
            },
        ),
    ]
