# Generated by Django 5.2.17 on 2026-09-29 12:48

import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PiscineRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Turn the next-piscine alert on or off.')),
                ('next_piscine_date', models.DateField(blank=True, help_text='Date the next piscine starts.', null=True)),
                ('message', models.CharField(blank=True, help_text='Optional custom text. Leave blank for the default message.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'next piscine registration',
                'verbose_name_plural': 'next piscine registration',
            },
        ),
        migrations.CreateModel(
            name='ImpactUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('information', models.TextField(blank=True, help_text='The impact story.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the website.')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_images', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'impact update',
                'verbose_name_plural': 'impact',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('information', models.TextField(blank=True, help_text='The news story.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the website.')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_images', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'news update',
                'verbose_name_plural': 'news',
                'ordering': ['-published_at', 'order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('information', models.TextField(blank=True, help_text='Short blurb about the partner.')),
                ('logo', filer.fields.image.FilerImageField(blank=True, help_text='Square or wide logo, PNG/SVG preferred.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_logos', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='e.g. Lead Instructor', max_length=150)),
                ('bio', models.TextField(blank=True, help_text='Short biography.')),
                ('photo', filer.fields.image.FilerImageField(blank=True, help_text='Portrait photo of the staff member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_photos', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'staff member',
                'verbose_name_plural': 'staff',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
