# Generated by Django 5.2.17 on 2026-09-30 12:04

import core.indexes
import core.operations
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        # Required by the gin_trgm_ops operator class used below.
        core.operations.enable_trigram(),
        migrations.AddIndex(
            model_name='article',
            index=core.indexes.GinTrigramIndex(fields=['title'], name='article_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='article',
            index=core.indexes.GinTrigramIndex(fields=['summary'], name='article_summary_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='article',
            index=core.indexes.GinTrigramIndex(fields=['body'], name='article_body_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='article',
            index=core.indexes.GinTrigramIndex(fields=['slug'], name='article_slug_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='category',
            index=core.indexes.GinTrigramIndex(fields=['name'], name='category_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='category',
            index=core.indexes.GinTrigramIndex(fields=['slug'], name='category_slug_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='category',
            index=core.indexes.GinTrigramIndex(fields=['description'], name='category_description_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
