# Generated by Django 5.2.17 on 2026-09-29 17:41

import django.db.models.deletion
import filer.fields.file
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("filer", "0018_alter_file_options"),
        ("site_content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactupdate",
            name="report",
            field=filer.fields.file.FilerFileField(
                blank=True,
                help_text="Optional PDF report visitors can download from this impact story.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="impact_reports",
                to="filer.file",
            ),
        ),
    ]
