# Generated by Django 5.2.17 on 2026-09-29 18:43

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0002_impactupdate_report'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(help_text="URL segment, e.g. about-us. Use 'home' for the landing page.", max_length=100, unique=True)),
                ('title', models.CharField(help_text='Page name shown in the nav/header.', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional hero subtitle under the title.', max_length=255)),
                ('meta_title', models.CharField(blank=True, help_text='Optional SEO title. Falls back to the page title.', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='Optional SEO description.', max_length=300)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide from the website.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_image', filer.fields.image.FilerImageField(blank=True, help_text='Optional hero/banner image for the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_hero_images', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True, help_text='Section copy.')),
                ('cta_label', models.CharField(blank=True, help_text='Optional button text, e.g. Learn more.', max_length=100)),
                ('cta_url', models.CharField(blank=True, help_text='Optional button target: a path (/hire-talent) or full URL.', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_section_images', to=settings.FILER_IMAGE_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='site_content.page')),
            ],
            options={
                'verbose_name': 'page section',
                'verbose_name_plural': 'page sections',
                'ordering': ['order', 'id'],
            },
        ),
    ]
