# Generated by Django 5.2.17 on 2026-10-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0002_impactupdate_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='Internal path (e.g. /about) or a full external URL (https://...).', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the website.')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='Open this link in a new tab.')),
                ('show_chevron', models.BooleanField(default=False, help_text='Show a small dropdown chevron next to the label.')),
            ],
            options={
                'verbose_name': 'site link',
                'verbose_name_plural': 'site links',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
