# Generated by Django 5.2.17 on 2026-10-02

import core.indexes
import core.operations
import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Adds the editorial stream models (Category/Article) and their indexes.

    These models arrived on the ``seo`` branch, whose own ``0001_initial``
    created them. ``develop`` independently rewrote ``0001_initial`` for the
    block-content models, so on the merged history the two sets of tables have
    to be created in separate steps: the block content in ``0001``/``0002``,
    the editorial stream here.
    """

    dependencies = [
        ("filer", "0018_alter_file_options"),
        ("site_content", "0002_impactupdate_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="site_content.category",
                    ),
                ),
                (
                    "cover_image",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_covers",
                        to=settings.FILER_IMAGE_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        # Required by the gin_trgm_ops operator class used below.
        core.operations.enable_trigram(),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["status", "published_at"], name="article_status_published_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=core.indexes.GinTrigramIndex(fields=["title"], name="article_title_trgm", opclasses=["gin_trgm_ops"]),
        ),
        migrations.AddIndex(
            model_name="article",
            index=core.indexes.GinTrigramIndex(fields=["summary"], name="article_summary_trgm", opclasses=["gin_trgm_ops"]),
        ),
        migrations.AddIndex(
            model_name="article",
            index=core.indexes.GinTrigramIndex(fields=["body"], name="article_body_trgm", opclasses=["gin_trgm_ops"]),
        ),
        migrations.AddIndex(
            model_name="article",
            index=core.indexes.GinTrigramIndex(fields=["slug"], name="article_slug_trgm", opclasses=["gin_trgm_ops"]),
        ),
        migrations.AddIndex(
            model_name="category",
            index=core.indexes.GinTrigramIndex(fields=["name"], name="category_name_trgm", opclasses=["gin_trgm_ops"]),
        ),
        migrations.AddIndex(
            model_name="category",
            index=core.indexes.GinTrigramIndex(fields=["slug"], name="category_slug_trgm", opclasses=["gin_trgm_ops"]),
        ),
        migrations.AddIndex(
            model_name="category",
            index=core.indexes.GinTrigramIndex(fields=["description"], name="category_description_trgm", opclasses=["gin_trgm_ops"]),
        ),
        # The block-content models gained trigram indexes on this branch too,
        # so their admin searches stay index-backed (see TrigramSearchMixin).
        migrations.AddIndex(
            model_name="impactupdate",
            index=core.indexes.GinTrigramIndex(fields=["title"], name="impact_title_trgm", opclasses=["gin_trgm_ops"]),
        ),
        migrations.AddIndex(
            model_name="newsupdate",
            index=core.indexes.GinTrigramIndex(fields=["title"], name="news_title_trgm", opclasses=["gin_trgm_ops"]),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=core.indexes.GinTrigramIndex(fields=["name"], name="partner_name_trgm", opclasses=["gin_trgm_ops"]),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=core.indexes.GinTrigramIndex(fields=["name"], name="staff_name_trgm", opclasses=["gin_trgm_ops"]),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=core.indexes.GinTrigramIndex(fields=["role"], name="staff_role_trgm", opclasses=["gin_trgm_ops"]),
        ),
    ]
