# Generated by Django 5.2.17 on 2026-10-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0003_article_category_and_trigram_indexes'),
        ('site_content', '0004_seed_pages'),
    ]

    operations = [
    ]
