# Generated by Django 5.2.17 on 2026-10-08 09:45

from django.db import migrations, models


def copy_existing_piscine_date(apps, schema_editor):
    """Move the singleton's single date into the new PiscineDate list."""
    PiscineRegistration = apps.get_model("site_content", "PiscineRegistration")
    PiscineDate = apps.get_model("site_content", "PiscineDate")
    for registration in PiscineRegistration.objects.exclude(next_piscine_date=None):
        PiscineDate.objects.create(date=registration.next_piscine_date, is_active=True)


def remove_copied_piscine_date(apps, schema_editor):
    """No-op reverse: the source field is restored by the schema operation."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0006_merge_sitelinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiscineDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date this piscine starts (09:00 EAT).')),
                ('label', models.CharField(blank=True, help_text='Optional label for this date. Leave blank for the default.', max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this date from the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'piscine date',
                'verbose_name_plural': 'piscine dates',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.RunPython(
            copy_existing_piscine_date,
            remove_copied_piscine_date,
        ),
        migrations.RemoveField(
            model_name='piscineregistration',
            name='next_piscine_date',
        ),
    ]
