# Generated by Django 5.2.17 on 2026-10-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('path', models.CharField(help_text='Path on the frontend, e.g. /about or /register.', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to stop checking this page.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first on the status board.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'frontend page',
                'verbose_name_plural': 'frontend pages',
                'ordering': ['order', 'id'],
            },
        ),
    ]
