# Generated by Django 5.2.17 on 2026-09-30 12:04

import core.indexes
import core.operations
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_applicant_applicant_first_name_trgm_and_more'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        # Required by the gin_trgm_ops operator class used below.
        core.operations.enable_trigram(),
        migrations.AddIndex(
            model_name='event',
            index=core.indexes.GinTrigramIndex(fields=['title'], name='event_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='event',
            index=core.indexes.GinTrigramIndex(fields=['summary'], name='event_summary_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='event',
            index=core.indexes.GinTrigramIndex(fields=['description'], name='event_description_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='event',
            index=core.indexes.GinTrigramIndex(fields=['location_name'], name='event_location_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='event',
            index=core.indexes.GinTrigramIndex(fields=['slug'], name='event_slug_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=core.indexes.GinTrigramIndex(fields=['full_name'], name='eventreg_full_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=core.indexes.GinTrigramIndex(fields=['email'], name='eventreg_email_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=core.indexes.GinTrigramIndex(fields=['phone'], name='eventreg_phone_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
