# Generated by Django 5.2.17 on 2026-09-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('undisclosed', 'Prefer not to say')], max_length=20)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('education_level', models.CharField(blank=True, choices=[('secondary', 'Secondary school'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('degree', "Bachelor's degree"), ('postgraduate', 'Postgraduate'), ('self_taught', 'Self-taught'), ('other', 'Other')], max_length=20)),
                ('current_occupation', models.CharField(blank=True, max_length=150)),
                ('motivation', models.TextField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('referral_source', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('screening', 'Screening'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='applicants__status_b4e2c4_idx'), models.Index(fields=['county'], name='applicants__county_906b0d_idx')],
            },
        ),
    ]
