# Generated by Django 5.2.17 on 2026-09-30 12:04

import core.indexes
import core.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        # Required by the gin_trgm_ops operator class used below.
        core.operations.enable_trigram(),
        migrations.AddIndex(
            model_name='applicant',
            index=core.indexes.GinTrigramIndex(fields=['first_name'], name='applicant_first_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=core.indexes.GinTrigramIndex(fields=['last_name'], name='applicant_last_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=core.indexes.GinTrigramIndex(fields=['email'], name='applicant_email_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=core.indexes.GinTrigramIndex(fields=['phone'], name='applicant_phone_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=core.indexes.GinTrigramIndex(fields=['county'], name='applicant_county_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=core.indexes.GinTrigramIndex(fields=['current_occupation'], name='applicant_occupation_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=core.indexes.GinTrigramIndex(fields=['motivation'], name='applicant_motivation_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
